FROM python:3.12

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY geo_analytics geo_analytics
COPY config config
COPY MadridRestaurantsNotebook.ipynb .

RUN mkdir -p /app/data